# Generated by Django 2.2.4 on 2021-01-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Your Name :')),
                ('profile', models.CharField(max_length=100, verbose_name='Your Profile :')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='Your E-Mail :')),
                ('mobile', models.CharField(max_length=15, unique=True, verbose_name='Your Mobile : ')),
                ('image', models.ImageField(upload_to='about', verbose_name='Upload Image : ')),
                ('description', models.TextField(max_length=600, verbose_name='About You : ')),
            ],
            options={
                'db_table': 'about',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='blog Title : ')),
                ('image', models.ImageField(upload_to='blog', verbose_name='Upload Image : ')),
                ('datetime', models.DateTimeField(verbose_name='DataTime')),
                ('description', models.TextField(max_length=600, verbose_name='blog Description : ')),
            ],
            options={
                'db_table': 'blog',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Portfolio Title : ')),
                ('image', models.ImageField(upload_to='portfolio', verbose_name='Upload Image : ')),
                ('datetime', models.DateTimeField(verbose_name='DataTime')),
                ('description', models.TextField(max_length=600, verbose_name='Portfolio Description : ')),
            ],
            options={
                'db_table': 'portfolio',
            },
        ),
        migrations.CreateModel(
            name='Sevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Service Title : ')),
                ('description', models.TextField(max_length=600, verbose_name='Service Description : ')),
            ],
            options={
                'db_table': 'service',
            },
        ),
    ]
